//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammlung.Pipes.Werkzeug.Resources {
    using System;
    
    internal class Lang {
        /// <summary>
        ///   Looks up a localized string similar to in one of the intervals {0}.
        /// </summary>
        internal static string Validation_Interval_Exc_MultiInterval => "in one of the intervals {0}";

        /// <summary>
        ///   Looks up a localized string similar to Expected value {0} to be {1}..
        /// </summary>
        internal static string Validation_Interval_Exc_Reason => "Expected value {0} to be {1}.";

        /// <summary>
        ///   Looks up a localized string similar to in the interval {0}.
        /// </summary>
        internal static string Validation_Interval_Exc_SingleInterval => "in the interval {0}";

        /// <summary>
        ///   Looks up a localized string similar to Expected value {0} to match regular expression {1}..
        /// </summary>
        internal static string Validation_Regex_Exc_Reason => "Expected value {0} to match regular expression {1}.";
    }
}
