//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammlung.Collections.Dictionaries.Resources {
    using System;
    
    internal class ErrorMessages {
        /// <summary>
        ///   Looks up a localized string similar to Duplicate key {0}..
        /// </summary>
        internal static string DuplicateKeyError => "Duplicate key {0}.";
    }
}
