//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammlung.Numerics.Resources {
    using System;

    internal class ErrorMessages {
        /// <summary>
        ///   Looks up a localized string similar to The interval {0} is an invalid interval..
        /// </summary>
        internal static string IntervalInvalid => "The interval {0} is invalid.";

        /// <summary>
        ///   Looks up a localized string similar to Value is expected to be inside the interval {0}.
        /// </summary>
        internal static string ParamRequireElementOf => "Value is expected to be inside the interval {0}";
    }
}
