//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammlung.Collections.Resources {
    using System;
    
    internal class ErrorMessages {
        /// <summary>
        ///   Looks up a localized string similar to The element {0} could not be found..
        /// </summary>
        internal static string ElementNotFoundError => "The element {0} could not be found.";

        /// <summary>
        ///   Looks up a localized string similar to The collection is empty..
        /// </summary>
        internal static string EmptyCollectionError => "The collection is empty.";
    }
}
