//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sammlung.Werkzeug.Resources {
    using System;

    internal class ErrorMessages
    {
        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to have at least {0} elements, but actually there were {1}..
        /// </summary>
        internal static string ParamRequireAtLeastNumElements =>
            "The parameter is expected to have at least {0} elements, but actually there were {1}.";

        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to have at most {0} elements, but actually there were {1}..
        /// </summary>
        internal static string ParamRequireAtMostNumElements =>
            "The parameter is expected to have at most {0} elements, but actually there were {1}.";

        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to be equal to {0}..
        /// </summary>
        internal static string ParamRequiredEqual => "The parameter is expected to be equal to {0}.";

        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to be greater than {0}..
        /// </summary>
        internal static string ParamRequiredGreater => "The parameter is expected to be greater than {0}.";

        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to be greater than or equal to {0}..
        /// </summary>
        internal static string ParamRequiredGreaterEqual =>
            "The parameter is expected to be greater than or equal to {0}.";

        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to be less than {0}..
        /// </summary>
        internal static string ParamRequiredLess => "The parameter is expected to be less than {0}.";

        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to be less than or equal to {0}..
        /// </summary>
        internal static string ParamRequiredLessEqual => "The parameter is expected to be less than or equal to {0}.";

        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to be not null..
        /// </summary>
        internal static string ParamRequiredNotNull => "The parameter is expected to be not null.";

        /// <summary>
        ///   Looks up a localized string similar to The parameter is expected to have exactly {0} elements, but actually there were {1}..
        /// </summary>
        internal static string ParamRequireExactlyNumElements =>
            "The parameter is expected to have exactly {0} elements, but actually there were {1}.";

        /// <summary>
        ///   Looks up a localized string similar to The string parameter {0} is expected to be not null or empty..
        /// </summary>
        internal static string ParamStringRequiredNotNullOrEmpty =>
            "The string parameter {0} is expected to be not null or empty.";
    }
}
