name: DocFx

on:
  workflow_dispatch: []
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
    
jobs:
  generate-and-public-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: .docfx/docfx.json
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      env:
        GH_PATH: ${{ secrets.GH_PATH }}
      with:
        target_branch: gh-pages
        build_dir: .docfx/_site
        jekyll: false
