name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack --no-build --include-symbols --include-source --configuration Release -p:SymbolPackageFormat=snupkg
    - name: Upload the NuGet package
      uses: actions/upload-artifact@v2.2.1
      with:
        path: "**/*.nupkg"
    - name: Upload the NuGet symbol package
      uses: actions/upload-artifact@v2.2.1
      with:
        path: "**/*.snupkg"
