name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore NuGet Packages
      run: nuget restore Sammlung.sln
    - name: Build
      run: msbuild -t:Build -p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Package
      run: msbuild -t:Pack -p:Configuration=Release
    - name: Pushing NuGet packages to nuget.org
      run: dotnet nuget push **/*.*nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
