name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore NuGet Packages
      run: nuget restore SimpleFrameworkApp.sln
    - name: Build
      run: msbuild -t:Build -p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Build
      run: msbuild -t:Pack -p:Configuration=Release
    - name: Upload the NuGet package
      uses: actions/upload-artifact@v2.2.1
      with:
        path: "**/*.nupkg"
    - name: Upload the NuGet symbol package
      uses: actions/upload-artifact@v2.2.1
      with:
        path: "**/*.snupkg"
